[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.4,<4"]

[project]
authors = [{name = "xinetzone", email = "735613050@qq.com"}]
dynamic = ["version", "description"]
license = {file = "LICENSE"}
name = "thinking"
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
  "sphinx>=4.4,<5",
  "pydata_sphinx_theme",
]

maintainers = [
  {name = "xinetzone", email = "735613050@qq.com"},
]

classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python :: 3",
  "Framework :: Sphinx",
  "Framework :: Sphinx :: Theme",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent",
]

[project.urls]
Home = "https://github.com/xinetzone/thinking"

[project.optional-dependencies]
doc = [
  "myst-nb",
  "pytest",
  "pytest-regressions",
  "sphinxext-rediraffe",
  "sphinx_copybutton",
  "invoke",
]

coverage = [
  "pytest-cov",
  "codecov",
  "thinking[test]",
]
dev = [
  "pyyaml",
  "pre-commit",
  "thinking[coverage]",
]
test = [
  "pytest",
  "thinking[doc]",
]

[project.entry-points]
"sphinx.html_themes" = {thinking = "thinking"}

[tool.flit.sdist]
# include = ["docs/"]
exclude = ['docs', '.git', '.github']
